name: Android Bluetooth Build  # 第 1 行

on: [push, workflow_dispatch]   # 第 2 行

jobs:                           # 第 3 行
  build:                        # 第 4 行
    runs-on: ubuntu-latest       # 第 5 行 - 正确缩进
    
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          build-tools-version: '34.0.0'
          platform-version: 'android-34'
          sdk-licenses: true
          
      - name: Create Gradle wrapper
        run: |
          if [ ! -f "gradlew" ]; then
            gradle wrapper --gradle-version=8.4
            chmod +x gradlew
          fi
          
      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          
      - name: Build APK
        run: |
          ./gradlew assembleDebug --stacktrace
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bluetooth-app
          path: app/build/outputs/apk/debug/*.apk
