name: Android Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_VERSION: "8.4"
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
    
    steps:
    - uses: actions/checkout@v4
    
    # 1. 更新 Gradle 到指定版本
    - name: Update Gradle wrapper
      run: |
        # 如果存在旧的 wrapper 文件则删除
        [ -f gradlew ] && rm gradlew || true
        [ -f gradlew.bat ] && rm gradlew.bat || true
        
        # 使用正确的 Gradle 版本创建新包装器
        ./gradle-8.4/bin/gradle wrapper --gradle-version=${{ env.GRADLE_VERSION }}
        chmod +x gradlew
        
    # 2. 设置 Java 环境
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    # 3. 设置 Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        build-tools-version: '34.0.0'
        platform-version: 'android-34'
        sdk-licenses: true
    
    # 4. 创建 Android SDK 配置
    - name: Create Android config
      run: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
        echo "android.useAndroidX=true" >> gradle.properties
        echo "android.enableJetifier=true" >> gradle.properties
    
    # 5. 执行构建
    - name: Build APK
      run: |
        ./gradlew assembleDebug --stacktrace --no-daemon \
          -Dorg.gradle.jvmargs=-Xmx2048m
    
    # 6. 上传结果
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: bluetooth-app
        path: app/build/outputs/apk/debug/*.apk
