#!/bin/bash
# 修复工作流配置脚本

# 创建工作流目录
mkdir -p .github/workflows

# 下载正确的工作流文件
curl -L -o .github/workflows/android-build.yml \
  https://gist.githubusercontent.com/android-helper/valid-android-workflow/raw/main/android-build.yml

# 提交更改
git add .github/workflows/android-build.yml
git commit -m "修复工作流配置"
git push

echo "工作流已修复，请查看 GitHub Actions"
