  - name: Build APK
  run: |
    # 递归修复权限问题
    find . -name "*.sh" -exec chmod +x {} \;
    find . -name "*.bat" -exec chmod +x {} \;
    chmod +x gradlew
    
    # 执行构建
    ./gradlew assembleDebug
