name: Android Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Fix permissions (关键修复)
      run: |
        # 修复 gradlew 权限
        if [ -f "gradlew" ]; then
          chmod +x gradlew
        else
          echo "gradlew not found, creating..."
          ./gradle-8.3/bin/gradle wrapper --gradle-version 8.3
          chmod +x gradlew
        fi
        
        # 修复其他文件权限
        find . -name "*.sh" -exec chmod +x {} \;
        ls -l gradlew
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        build-tools-version: '34.0.0'
        platform-version: 'android-34'
        sdk-licenses: true  # 自动接受许可证
        
    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
        echo "ndk.dir=$ANDROID_SDK_ROOT/ndk/25.1.8937393" >> local.properties
        cat local.properties
        
    - name: Build with Gradle
      run: |
        # 确保权限正确
        chmod +x gradlew
        
        # 执行构建
        ./gradlew assembleDebug --stacktrace --no-daemon
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: bluetooth-app
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 30
