name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

    strategy:
      matrix:
        java-version: [17]
        android-build-tools: ['34.0.0']
        target-sdk: [34]

    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        sdk-path: ${{ env.ANDROID_SDK_ROOT }}
        sdk-platform: android-${{ matrix.target-sdk }}
        sdk-build-tools: ${{ matrix.android-build-tools }}
        sdk-licenses: true  # 自动接受许可证
        
    - name: Build APK
      run: |
        # 创建必要的本地文件
        echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
        echo "ndk.dir=$ANDROID_SDK_ROOT/ndk/25.1.8937393" >> local.properties
        
        # 执行编译
        ./gradlew assembleDebug --stacktrace
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: |
          app/build/outputs/apk/**/*.apk
          app/build/outputs/mapping/release/mapping.txt
        if-no-files-found: error
        retention-days: 30
