name: Android Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Fix Gradle files
      run: |
        # 修复所有非法注释
        find . -name "*.gradle" -exec sed -i 's/^#/\/\//g' {} \;
        find . -name "*.gradle" -exec sed -i 's/#.*//g' {} \;
        
        # 验证 settings.gradle
        cat settings.gradle
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        build-tools-version: '34.0.0'
        platform-version: 'android-34'
        sdk-licenses: true  # 自动接受许可证
        
    - name: Fix permissions
      run: |
        # 确保权限正确
        chmod +x gradlew
        chmod +r gradle/wrapper/gradle-wrapper.jar
        sudo chmod -R a+rwx .
        
    - name: Build APK
      run: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
        ./gradlew assembleDebug --stacktrace --no-daemon
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: bluetooth-remote-app
        path: app/build/outputs/apk/debug/*.apk
